language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FGMov88dVnkIzlAYJTHWoZJP/dtkPLDhS1EbDj27IK1NonPhgPjZx5QeWBiBlroTnro25zczlbJnFjC60dSzGsewIpTYLDRE7AA69uger3GdCX+3XV/GtYtghkbv4xvnVH7JfOjXC4TI+/mLQh0WAjriXBtbuEX6jYn0XEEqthJpRhGQNeaZBzGMeE6d2icIvvFUBnbCv6FY0AsVYMJJ8cBdMXiUY9MHilpBrIlCkToz74U++XmYcbANYblzBhXBGIJunekerHzgwosL7Dk/isB7T/YHGxD7MURUN9o3fIAiYJHhU0IIu+v0Imsc41uMofOfr98j6n0eQf0uhBEVyp01GC2SISkA+O5R4GCoY8NDVB7STWRucn/4r7unhJ0zXwEG8MbSMC9Yf6fVoLwZ7iSTlT4Hrck1fv4GMkMvF6HVmVC1EVIS4oonUcUEKBLKBJ0vKWN5XLIdiKIQ4Q0Jr0IPbjV1O1EIrE4eGyjKrA/s4Ovi/p+EWBMpWET38++BjqxBWjL5fTT9wn6okUuL5APUiiMMs309FkXSKMijHzcAO8Qi4ddzaUHohnHx2sDWKj4+W5XUv0qudoggilfuFdbuAbR4O9TsowKkqRBeQmWlfaXumzg9VN51D8N9YUEKnCYEG6bruFHqOFPceapx728EtHZeUM6GU3AC44NO9Ao="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "e-gov/DVK"
      description: "Build submitted via Travis CI"
    notification_email: hannes.kiivet@ria.ee
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan