ALTER TABLE allkiri ADD CONSTRAINT allkiri_id_pkey PRIMARY KEY (allkiri_id);
ALTER TABLE allyksus ADD CONSTRAINT allyksus_pkey_id_pkey PRIMARY KEY (id);
ALTER TABLE vahendaja ADD CONSTRAINT vahendaja_id_pkey PRIMARY KEY (vahendaja_id);
ALTER TABLE oigus_antud ADD CONSTRAINT oigus_antud_id_pkey PRIMARY KEY (oigus_antud_id);
ALTER TABLE ametikoht ADD CONSTRAINT ametikoht_id_pkey PRIMARY KEY (ametikoht_id);
ALTER TABLE dokumendi_fragment ADD CONSTRAINT dokumendi_fragment_fragment_id_pkey PRIMARY KEY (fragment_id);
ALTER TABLE vastuvotja_staatus ADD CONSTRAINT vastuvotja_staatus_id_pkey PRIMARY KEY (vastuvotja_staatus_id);
ALTER TABLE klassifikaator ADD CONSTRAINT klassifikaator_id_pkey PRIMARY KEY (klassifikaator_id);
ALTER TABLE dokumendi_fail ADD CONSTRAINT dokumendi_fail_id_pkey PRIMARY KEY (fail_id);
ALTER TABLE vastuvotja_mall ADD CONSTRAINT vastuvotja_mall_id_pkey PRIMARY KEY (vastuvotja_mall_id);
ALTER TABLE saatja ADD CONSTRAINT saatja_id_pkey PRIMARY KEY (saatja_id);
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_id_pkey PRIMARY KEY (vastuvotja_id);
ALTER TABLE staatuse_ajalugu ADD CONSTRAINT staatuse_ajalugu_id_pkey PRIMARY KEY (staatuse_ajalugu_id);
ALTER TABLE dynaamilised_metaandmed ADD CONSTRAINT dynaamilised_metaandmed_pkey PRIMARY KEY (dokument_id,nimi);
ALTER TABLE isik ADD CONSTRAINT isiki_id_pkey PRIMARY KEY (i_id);
ALTER TABLE ametikoht_taitmine ADD CONSTRAINT ametikoht_taitmine_id_pkey PRIMARY KEY (taitmine_id);
ALTER TABLE asutus ADD CONSTRAINT asutus_registrikood_un UNIQUE (registrikood);
ALTER TABLE asutus ADD CONSTRAINT asutus_id_pkey PRIMARY KEY (asutus_id);
ALTER TABLE dokumendi_ajalugu ADD CONSTRAINT dokumendi_ajalugu_id_pkey PRIMARY KEY (ajalugu_id);
ALTER TABLE dokument ADD CONSTRAINT dokumendi_id_pkey PRIMARY KEY (dokument_id);
ALTER TABLE ehak ADD CONSTRAINT ehak_id_pkey PRIMARY KEY (ehak_id);
ALTER TABLE kaust ADD CONSTRAINT kaust_id_pkey PRIMARY KEY (kaust_id);
ALTER TABLE oigus_objektile ADD CONSTRAINT oigus_objektile_id_pkey PRIMARY KEY (oigus_objektile_id);
ALTER TABLE transport ADD CONSTRAINT transport_id_pkey PRIMARY KEY (transport_id);
ALTER TABLE konversioon ADD CONSTRAINT konversioon_id_pkey PRIMARY KEY (id);
ALTER TABLE klassifikaatori_tyyp ADD CONSTRAINT klassifikaatori_id_pkey PRIMARY KEY (klassifikaatori_tyyp_id);
ALTER TABLE logi ADD CONSTRAINT logi_id_pkey PRIMARY KEY (log_id);
ALTER TABLE server ADD CONSTRAINT server_id_pkey PRIMARY KEY (server_id);
ALTER TABLE dokumendi_metaandmed ADD CONSTRAINT dokument_meta_id_pkey PRIMARY KEY (dokument_id);

ALTER TABLE allkiri ADD CONSTRAINT allkiri_dokument_id_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE allyksus ADD CONSTRAINT allyksus_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE CASCADE;
ALTER TABLE allyksus ADD CONSTRAINT allyksus_vanem_id_fkey FOREIGN KEY (vanem_id) REFERENCES allyksus(id) ON DELETE CASCADE;
ALTER TABLE vahendaja ADD CONSTRAINT vahendaja_transport_id_fkey FOREIGN KEY (transport_id) REFERENCES transport (transport_id) ON DELETE CASCADE;
ALTER TABLE vahendaja ADD CONSTRAINT vahendaja_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus (asutus_id) ON DELETE CASCADE;
ALTER TABLE vahendaja ADD CONSTRAINT vahendaja_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht (ametikoht_id) ON DELETE CASCADE;
ALTER TABLE oigus_antud ADD CONSTRAINT oigus_antud_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus (asutus_id) ON DELETE CASCADE;
ALTER TABLE oigus_antud ADD CONSTRAINT oigus_antud_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht(ametikoht_id) ON DELETE CASCADE;
ALTER TABLE ametikoht ADD CONSTRAINT ametikoht_allyksus_id_fkey FOREIGN KEY (allyksus_id) REFERENCES allyksus(id) ON DELETE SET NULL;
ALTER TABLE ametikoht ADD CONSTRAINT ametikoht_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE CASCADE;
ALTER TABLE klassifikaator ADD CONSTRAINT klassifikaator_tyyp_id_fkey FOREIGN KEY (klassifikaatori_tyyp_id) REFERENCES klassifikaatori_tyyp(klassifikaatori_tyyp_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dokumendi_fail ADD CONSTRAINT dokumendi_fail_document_id_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja_mall ADD CONSTRAINT vastuvotja_mall_saatmisviis_id_fkey FOREIGN KEY (saatmisviis_id) REFERENCES klassifikaator(klassifikaator_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja_mall ADD CONSTRAINT vastuvotja_mall_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja_mall ADD CONSTRAINT vastuvotja_mall_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht(ametikoht_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja_mall ADD CONSTRAINT vastuvotja_mall_allyksus_id_fkey FOREIGN KEY (allyksus_id) REFERENCES allyksus(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE saatja ADD CONSTRAINT saatja_transport_id_fkey FOREIGN KEY (transport_id) REFERENCES transport(transport_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE saatja ADD CONSTRAINT saatja_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE saatja ADD CONSTRAINT saatja_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht(ametikoht_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_transport_id_fkey FOREIGN KEY (transport_id) REFERENCES transport(transport_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_saatmisviis_id_fkey FOREIGN KEY (saatmisviis_id) REFERENCES klassifikaator(klassifikaator_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_staatus_id_fkey FOREIGN KEY (staatus_id) REFERENCES klassifikaator(klassifikaator_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht(ametikoht_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE vastuvotja ADD CONSTRAINT vastuvotja_vastuvotja_staatus_id_fkey FOREIGN KEY (vastuvotja_staatus_id) REFERENCES vastuvotja_staatus(vastuvotja_staatus_id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE staatuse_ajalugu ADD CONSTRAINT staatuse_ajalugu_vastuvotja_id_fkey FOREIGN KEY (vastuvotja_id) REFERENCES vastuvotja(vastuvotja_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE staatuse_ajalugu ADD CONSTRAINT staatuse_ajalugu_staatus_id_fkey FOREIGN KEY (staatus_id) REFERENCES klassifikaator(klassifikaator_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dynaamilised_metaandmed ADD CONSTRAINT dynaamilised_metaandmed_dokument_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ametikoht_taitmine ADD CONSTRAINT ametikoht_taitmine_i_id_fkey FOREIGN KEY (i_id) REFERENCES isik(i_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ametikoht_taitmine ADD CONSTRAINT ametikoht_taitmine_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht(ametikoht_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE asutus ADD CONSTRAINT asutus_ks_asutus_id_fkey FOREIGN KEY (ks_asutus_id) REFERENCES asutus(asutus_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dokumendi_ajalugu ADD CONSTRAINT dokumendi_ajalugu_dokument_id_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dokument ADD CONSTRAINT dokument_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dokument ADD CONSTRAINT dokument_kaust_id_fkey FOREIGN KEY (kaust_id) REFERENCES kaust(kaust_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dokument ADD CONSTRAINT dokument_eelmise_versiooni_id_fkey FOREIGN KEY (eelmise_versiooni_id) REFERENCES dokument(dokument_id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE kaust ADD CONSTRAINT kaust_ylemkaust_id_fkey FOREIGN KEY (ylemkaust_id) REFERENCES kaust(kaust_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE kaust ADD CONSTRAINT kaust_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE oigus_objektile ADD CONSTRAINT oigus_objektile_asutus_id_fkey FOREIGN KEY (asutus_id) REFERENCES asutus(asutus_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE oigus_objektile ADD CONSTRAINT oigus_objektile_ametikoht_id_fkey FOREIGN KEY (ametikoht_id) REFERENCES ametikoht(ametikoht_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE oigus_objektile ADD CONSTRAINT oigus_objektile_dokument_id_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE oigus_objektile ADD CONSTRAINT oigus_objektile_kaust_id_fkey FOREIGN KEY (kaust_id) REFERENCES kaust(kaust_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE transport ADD CONSTRAINT transport_dokument_id_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE transport ADD CONSTRAINT transport_staatus_id_fkey FOREIGN KEY (staatus_id) REFERENCES klassifikaator(klassifikaator_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dokumendi_metaandmed ADD CONSTRAINT dokumendi_metaandmed_id_fkey FOREIGN KEY (dokument_id) REFERENCES dokument(dokument_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;


ALTER TABLE allkiri ENABLE TRIGGER ALL;
ALTER TABLE allyksus ENABLE TRIGGER ALL;
ALTER TABLE ametikoht ENABLE TRIGGER ALL;
ALTER TABLE ametikoht_taitmine ENABLE TRIGGER ALL;
ALTER TABLE asutus ENABLE TRIGGER ALL;
ALTER TABLE dokumendi_ajalugu ENABLE TRIGGER ALL;
ALTER TABLE dokumendi_fail ENABLE TRIGGER ALL;
ALTER TABLE dokumendi_fragment ENABLE TRIGGER ALL;
ALTER TABLE dokumendi_metaandmed ENABLE TRIGGER ALL;
ALTER TABLE dokument ENABLE TRIGGER ALL;
ALTER TABLE dynaamilised_metaandmed ENABLE TRIGGER ALL;
ALTER TABLE ehak ENABLE TRIGGER ALL;
ALTER TABLE isik ENABLE TRIGGER ALL;
ALTER TABLE kaust ENABLE TRIGGER ALL;
ALTER TABLE klassifikaator ENABLE TRIGGER ALL;
ALTER TABLE klassifikaatori_tyyp ENABLE TRIGGER ALL;
ALTER TABLE konversioon ENABLE TRIGGER ALL;
ALTER TABLE logi ENABLE TRIGGER ALL;
ALTER TABLE oigus_antud ENABLE TRIGGER ALL;
ALTER TABLE oigus_objektile ENABLE TRIGGER ALL;
ALTER TABLE parameetrid ENABLE TRIGGER ALL;
ALTER TABLE saatja ENABLE TRIGGER ALL;
ALTER TABLE server ENABLE TRIGGER ALL;
ALTER TABLE staatuse_ajalugu ENABLE TRIGGER ALL;
ALTER TABLE transport ENABLE TRIGGER ALL;
ALTER TABLE vahendaja ENABLE TRIGGER ALL;
ALTER TABLE vastuvotja ENABLE TRIGGER ALL;
ALTER TABLE vastuvotja_mall ENABLE TRIGGER ALL;
ALTER TABLE vastuvotja_staatus ENABLE TRIGGER ALL;
