GRANT USAGE ON SCHEMA dvk to dvk_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dvk TO dvk_user;
GRANT SELECT, UPDATE, INSERT, REFERENCES, TRIGGER, DELETE ON ALL TABLES IN SCHEMA dvk TO dvk_user;   
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dvk TO dvk_user;

GRANT USAGE ON SCHEMA dvklog to dvk_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dvklog TO dvk_user;
GRANT SELECT, UPDATE, INSERT, REFERENCES, TRIGGER, DELETE ON ALL TABLES IN SCHEMA dvklog TO dvk_user;   
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dvklog TO dvk_user;

GRANT CONNECT ON DATABASE postgres TO dvk_user;

ALTER USER dvk_user SET search_path = dvk, public;