GRANT USAGE ON SCHEMA dvk to dvkuser;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dvk TO dvkuser;
GRANT SELECT, UPDATE, INSERT, REFERENCES, TRIGGER, DELETE ON ALL TABLES IN SCHEMA dvk TO dvkuser;   
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dvk TO dvkuser;

GRANT USAGE ON SCHEMA dvklog to dvkuser;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dvklog TO dvkuser;
GRANT SELECT, UPDATE, INSERT, REFERENCES, TRIGGER, DELETE ON ALL TABLES IN SCHEMA dvklog TO dvkuser;   
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dvklog TO dvkuser;

GRANT CONNECT ON DATABASE postgres TO dvkuser;

ALTER USER dvkuser SET search_path = dvk, public;