ALTER TABLE VASTUVOTJA MODIFY ALLYKSUSE_LYHINIMETUS varchar2(25);

DROP INDEX "ALLYKSUS_LYHINIMETUS_IDX";

ALTER TABLE ALLYKSUS MODIFY LYHINIMETUS varchar2(25);

create index "ALLYKSUS_LYHINIMETUS_IDX" on "ALLYKSUS"(nvl(lyhinimetus,' '))
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);

ALTER TABLE SAATJA MODIFY ALLYKSUSE_LYHINIMETUS varchar2(25);
ALTER TABLE VASTUVOTJA_MALL MODIFY ALLYKSUSE_LYHINIMETUS varchar2(25);
ALTER TABLE VAHENDAJA MODIFY ALLYKSUSE_LYHINIMETUS varchar2(25);
