CREATE
TABLE   VASTUVOTJA_STAATUS
(
        VASTUVOTJA_STAATUS_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
        NIMETUS VARCHAR2(100) NOT NULL
)
/

ALTER
TABLE   VASTUVOTJA
ADD
(
	VASTUVOTJA_STAATUS_ID NUMBER(38,0) NULL,
        METAXML CLOB NULL
)
/

ALTER TABLE VASTUVOTJA
ADD CONSTRAINT FK_VASTUVOTJA_6
FOREIGN KEY (VASTUVOTJA_STAATUS_ID)
REFERENCING VASTUVOTJA_STAATUS (VASTUVOTJA_STAATUS_ID)
ON DELETE SET NULL
/

create or replace
procedure Get_NextRecipientID(
    recipient_id out number)
as
begin
    select  sq_vastuvotja_id.nextval
    into    Get_NextRecipientID.recipient_id
    from    dual;
end;
/

DROP TRIGGER tr_vastuvotja_id
/

DROP PROCEDURE add_recipient
/

DROP PROCEDURE update_recipient
/

/* Vastuvõtja staatuse võimalike väärtuste sisestamine */
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (1, 'Dokumente on puudu (Pooleli)');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (2, 'Järjekorras');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (3, 'Ootel');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (4, 'Lõpetatud');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (5, 'Tagasi lükatud');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (6, 'Teha');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (7, 'Töötlemisel');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (8, 'Aktsepteeritud (Võetud töösse)');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (9, 'Salvestatud');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (10, 'Arhiveeritud');
INSERT
INTO    VASTUVOTJA_STAATUS(VASTUVOTJA_STAATUS_ID, NIMETUS)
VALUES  (11, 'Saadetud');


ALTER
TABLE   AMETIKOHT
MODIFY  ASUTUS_ID NOT NULL
/
