package dvk.api.ml;

import java.lang.reflect.Field;

import dvk.api.IOrganizationObserver;
import dvk.api.DVKAPI.DvkType;

// Generated 4.02.2010 13:44:05 by Hibernate Tools 3.2.4.GA

/**
 * DhlOrganization generated by hbm2java
 */
public class PojoOrganization implements IOrganizationObserver, java.io.Serializable
{
	final static String PojoName = PojoOrganization.class.getName();

	public static class FieldNames
	{
		public static final String orgCode = "orgCode";
		public static final String orgName = "orgName";
		public static final String dhlCapable = "dhlCapable";
		public static final String dhlDirectCapable = "dhlDirectCapable";
		public static final String dhlDirectProducerName = "dhlDirectProducerName";
		public static final String dhlDirectServiceUrl = "dhlDirectServiceUrl";
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -962233166809642524L;
	protected String orgCode;
	protected String orgName;
	protected boolean dhlCapable;
	protected boolean dhlDirectCapable;
	protected String dhlDirectProducerName;
	protected String dhlDirectServiceUrl;

	public PojoOrganization() {
	}

	public PojoOrganization(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public boolean isDhlCapable() {
		return this.dhlCapable;
	}

	public void setDhlCapable(boolean dhlCapable) {
		this.dhlCapable = dhlCapable;
	}

	public boolean isDhlDirectCapable() {
		return this.dhlDirectCapable;
	}

	public void setDhlDirectCapable(boolean dhlDirectCapable) {
		this.dhlDirectCapable = dhlDirectCapable;
	}

	public String getDhlDirectProducerName() {
		return this.dhlDirectProducerName;
	}

	public void setDhlDirectProducerName(String dhlDirectProducerName) {
		this.dhlDirectProducerName = dhlDirectProducerName;
	}

	public String getDhlDirectServiceUrl() {
		return this.dhlDirectServiceUrl;
	}

	public void setDhlDirectServiceUrl(String dhlDirectServiceUrl) {
		this.dhlDirectServiceUrl = dhlDirectServiceUrl;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == this) {
			return true;
		}

		if (obj == null || !(obj instanceof PojoOrganization)) {
			return false;
		}

		PojoOrganization other = (PojoOrganization) obj;

		return Util.hasSameValue(orgCode, other.orgCode) && Util.hasSameValue(orgName, other.orgName)
			&& Util.hasSameValue(dhlCapable, other.dhlCapable) && Util.hasSameValue(dhlDirectCapable, other.dhlDirectCapable)
			&& Util.hasSameValue(dhlDirectProducerName, other.dhlDirectProducerName)
			&& Util.hasSameValue(dhlDirectServiceUrl, other.dhlDirectServiceUrl);
	}

	@Override
	public PojoOrganization clone() {
		PojoOrganization ret = new PojoOrganization();

		ret.orgCode = orgCode;
		ret.orgName = orgName;
		ret.dhlCapable = dhlCapable;
		ret.dhlDirectCapable = dhlDirectCapable;
		ret.dhlDirectProducerName = dhlDirectProducerName;
		ret.dhlDirectServiceUrl = dhlDirectServiceUrl;

		return ret;
	}

	@Override
	public String toString() {
		return Util.getDump(this);
	}

	public void printOutFields() {
		Field[] fields = getClass().getDeclaredFields();
		for (Field f : fields) {
			System.out.println("public final String " + f.getName() + " = \"" + f.getName() + "\";");
		}
	}

	public String getCode() {
		return orgCode;
	}

	public String getName() {
		return orgName;
	}

	public DvkType getType() {
		return DvkType.Organization;
	}
}
